#!/usr/bin/env node
// Walks the source data directory and creates lib/data/indexes.ts containing
// every category's index.json. The result is a single module imported once at
// build time, so browsing the catalog is instant with zero network round-trips.
//
// Run with: npm run build-indexes -- /path/to/premeth-data
//          (or set PREMETH_DATA_DIR env var)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const dataDir =
  process.argv[2] ||
  process.env.PREMETH_DATA_DIR ||
  path.resolve(ROOT, '../premeth-data-main');

if (!fs.existsSync(dataDir)) {
  console.error(`Data directory not found: ${dataDir}`);
  console.error('Usage: node scripts/build-indexes.mjs <path-to-premeth-data>');
  process.exit(1);
}

const categories = fs.readdirSync(dataDir, { withFileTypes: true })
  .filter((d) => d.isDirectory() && d.name !== 'scripts' && !d.name.startsWith('.'))
  .map((d) => d.name);

const indexes = {};
let totalPapers = 0;

for (const cat of categories) {
  const indexPath = path.join(dataDir, cat, 'index.json');
  if (!fs.existsSync(indexPath)) {
    console.warn(`Skipping ${cat}: no index.json`);
    continue;
  }
  try {
    const parsed = JSON.parse(fs.readFileSync(indexPath, 'utf8'));
    indexes[cat] = parsed;
    totalPapers += (parsed.papers || []).length;
  } catch (err) {
    console.warn(`Skipping ${cat}: ${err.message}`);
  }
}

const out = `// AUTO-GENERATED by scripts/build-indexes.mjs. Do not edit by hand.
// Re-run \`npm run build-indexes\` if the underlying data changes.

import type { CategoryIndex } from '../types';

export const INDEXES: Record<string, CategoryIndex> = ${JSON.stringify(indexes, null, 2)};
`;

const outPath = path.join(ROOT, 'lib/data/indexes.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out);

const kb = (fs.statSync(outPath).size / 1024).toFixed(1);
console.log(`Wrote ${Object.keys(indexes).length} categories, ${totalPapers} papers → lib/data/indexes.ts (${kb} KB)`);
